In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("loans_full_schema.csv")

In [6]:
df.head()

,Unnamed: 0,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,1,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,...,C3,Mar-18,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,2,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,...,C1,Feb-18,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,3,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,NaN,NaN,...,D1,Feb-18,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,4,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,...,A3,Jan-18,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,5,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,...,C3,Mar-18,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0

In [7]:
df.info

<bound method DataFrame.info of       Unnamed: 0                emp_title  emp_length state homeownership  \
0              1  global config engineer          3.0    NJ      MORTGAGE
1              2   warehouse office clerk        10.0    HI          RENT
2              3                 assembly         3.0    WI          RENT
3              4         customer service         1.0    PA          RENT
4              5     security supervisor         10.0    CA          RENT
...          ...                      ...         ...   ...           ...
9995        9996                   owner         10.0    TX          RENT
9996        9997                 director         8.0    PA      MORTGAGE
9997        9998                toolmaker        10.0    CT      MORTGAGE
9998        9999                  manager         1.0    WI      MORTGAGE
9999       10000       operations analyst         3.0    CT          RENT

      annual_income  verified_income  debt_to_income  annual_income_joint  \
0           90000.0         Verified           18.01                  NaN
1           40000.0     Not Verified            5.04                  NaN
2           40000.0  Source Verified           21.15                  NaN
3           30000.0     Not Verified           10.16                  NaN
4           35000.0         Verified           57.96              57000.0
...             ...              ...             ...                  ...
9995       108000.0  Source Verified           22.28                  NaN
9996       121000.0         Verified           32.38                  NaN
9997        67000.0         Verified           45.26             107000.0
9998        80000.0  Source Verified           11.99                  NaN
9999        66000.0     Not Verified           20.82                  NaN

     verification_income_joint  ...  sub_grade  issue_month  loan_status  \
0                          NaN  ...         C3       Mar-18      Current
1                          NaN  ...         C1       Feb-18      Current
2                          NaN  ...         D1       Feb-18      Current
3                          NaN  ...         A3       Jan-18      Current
4                     Verified  ...         C3       Mar-18      Current
...                        ...  ...        ...          ...          ...
9995                       NaN  ...         A4       Jan-18      Current
9996                       NaN  ...         D3       Feb-18      Current
9997           Source Verified  ...         E2       Feb-18      Current
9998                       NaN  ...         A1       Feb-18      Current
9999                       NaN  ...         B4       Feb-18      Current

      initial_listing_status  disbursement_method   balance  paid_total  \
0                      whole                 Cash  27015.86     1999.33
1                      whole                 Cash   4651.37      499.12
2                 fractional                 Cash   1824.63      281.80
3                      whole                 Cash  18853.26     3312.89
4                      whole                 Cash  21430.15     2324.65
...                      ...                  ...       ...         ...
9995                   whole                 Cash  21586.34     2969.80
9996                   whole                 Cash   9147.44     1456.31
9997              fractional                 Cash  27617.65     4620.80
9998                   whole                 Cash  21518.12     2873.31
9999                   whole                 Cash  11574.83     1658.56

      paid_principal  paid_interest  paid_late_fees
0             984.14        1015.19             0.0
1             348.63         150.49             0.0
2             175.37         106.43             0.0
3            2746.74         566.15             0.0
4            1569.85         754.80             0.0
...              ...            ...             ...
9995         2413.66         556.14             0.0
9996          852.56         603.75             0.0
9997         2382.35        2238.45             0.0
9998         2481.88         391.43             0.0
9999         1225.17         433.39             0.0

[10000 rows x 56 columns]>

In [8]:
customers = df[[
'emp_title',
'emp_length',
'state',
'homeownership',
'annual_income',
'verified_income',
]].drop_duplicates()

In [9]:
customers['customer_id'] = range(1, len(customers)+1)

In [10]:
df = df.merge(customers, on= [
'emp_title',
'emp_length',
'state',
'homeownership',
'annual_income',
'verified_income',
])

In [11]:
customers.head()

,emp_title,emp_length,state,homeownership,annual_income,verified_income,customer_id
0,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,1
1,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,2
2,assembly,3.0,WI,RENT,40000.0,Source Verified,3
3,customer service,1.0,PA,RENT,30000.0,Not Verified,4
4,security supervisor,10.0,CA,RENT,35000.0,Verified,5

In [12]:
loans = df[[
'loan_amount',
'term',
'interest_rate',
'installment',
'grade',
'sub_grade',
'loan_purpose',
'issue_month',
'customer_id',
]].copy()

In [13]:
loans['loan_id'] = range(1, len(loans)+1)

In [14]:
loans.head()

,loan_amount,term,interest_rate,installment,grade,sub_grade,loan_purpose,issue_month,customer_id,loan_id
0,28000,60,14.07,652.53,C,C3,moving,Mar-18,1,1
1,5000,36,12.61,167.54,C,C1,debt_consolidation,Feb-18,2,2
2,2000,36,17.09,71.40,D,D1,other,Feb-18,3,3
3,21600,36,6.72,664.19,A,A3,debt_consolidation,Jan-18,4,4
4,23000,36,14.07,786.87,C,C3,credit_card,Mar-18,5,5

In [18]:
df.columns

Index(['Unnamed: 0', 'emp_title', 'emp_length', 'state', 'homeownership',
       'annual_income', 'verified_income', 'debt_to_income',
       'annual_income_joint', 'verification_income_joint',
       'debt_to_income_joint', 'delinq_2y', 'months_since_last_delinq',
       'earliest_credit_line', 'inquiries_last_12m', 'total_credit_lines',
       'open_credit_lines', 'total_credit_limit', 'total_credit_utilized',
       'num_collections_last_12m', 'num_historical_failed_to_pay',
       'months_since_90d_late', 'current_accounts_delinq',
       'total_collection_amount_ever', 'current_installment_accounts',
       'accounts_opened_24m', 'months_since_last_credit_inquiry',
       'num_satisfactory_accounts', 'num_accounts_120d_past_due',
       'num_accounts_30d_past_due', 'num_active_debit_accounts',
       'total_debit_limit', 'num_total_cc_accounts', 'num_open_cc_accounts',
       'num_cc_carrying_balance', 'num_mort_accounts',
       'account_never_delinq_percent', 'tax_liens', 'public_record_bankrupt',
       'loan_purpose', 'application_type', 'loan_amount', 'term',
       'interest_rate', 'installment', 'grade', 'sub_grade', 'issue_month',
       'loan_status', 'initial_listing_status', 'disbursement_method',
       'balance', 'paid_total', 'paid_principal', 'paid_interest',
       'paid_late_fees', 'customer_id'],
      dtype='object')

In [19]:
credit_profile = df[[
'customer_id',
'total_credit_lines',
'open_credit_lines',
'total_credit_limit',
'delinq_2y',
'inquiries_last_12m',
'tax_liens',
'public_record_bankrupt']].drop_duplicates().copy()

In [20]:
credit_profile.head()

,customer_id,total_credit_lines,open_credit_lines,total_credit_limit,delinq_2y,inquiries_last_12m,tax_liens,public_record_bankrupt
0,1,28,10,70795,0,6,0,0
1,2,30,14,28800,0,1,0,1
2,3,31,10,24193,0,4,0,0
3,4,4,4,25400,0,0,1,0
4,5,22,16,69839,0,7,0,0

In [22]:
payments = df[[
'balance',
'paid_total',
'paid_principal',
'paid_interest',
'paid_late_fees']].copy()

In [23]:
payments['payment_id'] = range(1, len(payments)+1)

In [30]:
customers.to_csv("customers.csv", index=False)
loans.to_csv("loans.csv", index=False)
credit_profile.to_csv("credit_profile.csv", index=False)
payments.to_csv("payments.csv", index=False)

In [31]:
len(customers)
len(loans)
len(credit_profile)
len(payments)

10000

In [32]:
customers.csv
loans.csv
credit_profile.csv
payments.csv
loans_full_schema.csv

AttributeError: 'DataFrame' object has no attribute 'csv'

In [28]:
import os 
os.getcwd()

'C:\\Users\\Atishay Jain'

In [33]:
os.listdir()

['.anaconda',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.popsql.json',
 '.rustup',
 '.vscode',
 '14-02-2026 Python.ipynb',
 'anaconda3',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'credit_profile.csv',
 'customers.csv',
 'data_preparation.ipynb',
 'Documents',
 'Downloads',
 'Favorites',
 'ifood_df.csv',
 'Links',
 'loans.csv',
 'loans_full_schema.csv',
 'Local Settings',
 'Marketing_analysis.ipynb',
 'marketing_cleaned.csv',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{bae04efc-3cb2-11f0-843a-85ba34db6dc7}.TM.blf',
 'NTUSER.DAT{bae04efc-3cb2-11f0-843a-85ba34db6dc7}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{bae04efc-3cb2-11f0-843a-85ba34db6dc7}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'payments.csv',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos']